#!/usr/bin/env bash

curl -o /usr/local/bin/installimg https://cdn.rawgit.com/pratinav/disc-image-installer/master/installimg \
|| { echo 'File download failed! Installation aborted.' >&2; exit 1; }

chmod +x /usr/local/bin/installimg \
|| { echo 'Could not change file permissions! Installation aborted.' >&2; exit 1; }

echo 'Disc Image Installer has been installed succesfully.'
echo 'To use the image installer, run:'
echo '  installimg <disk> <disc image file path>'
echo 'For more information-  https://github.com/pratinav/disc-image-installer'

exit 0
